Feature/amm fe 12/created gallery
koshkinoko-hana/amm-fe pull request #21
Opened 2023-05-29 14:04 UTC by danil136

2023-05-31 13:45 UTC, koshkinoko-hana requested changes

2023-05-31 13:45 UTC, koshkinoko-hana commented on src/admin/ducks/sagas/gallery.ts
> +      const res: {data: GalleryPhotoListItem[], total: number} = yield call(get, `${apiAdmin}/gallery?offset=${action.payload}&limit=10`)
лучше передавать, а то у нас потом поменяется вдруг количество, а мы искать будем где же этот лимит выставляется

2023-05-31 13:45 UTC, koshkinoko-hana commented on src/admin/pages/createPhoto/index.tsx
> +    console.log(2)
кхъ

2023-05-31 13:45 UTC, koshkinoko-hana commented on src/client/components/pageHeader/pageHeader.scss
> +                bottom: 10px;
константа)

2023-05-31 13:45 UTC, koshkinoko-hana commented on src/client/pages/galleryPage/galleryPage.scss
> +    // margin: 0 auto;
удалить

2023-06-01 08:54 UTC, danil136 commented on src/admin/pages/createPhoto/index.tsx
> +    console.log(2)
ты не шаришь за тру дебагинг

2023-06-01 09:38 UTC, koshkinoko-hana approved these changes

2023-06-01 09:38 UTC, merged