added header to news page
koshkinoko-hana/amm-fe pull request #3
Opened 2023-05-15 11:02 UTC by 0obitouchiha0

2023-05-16 13:11 UTC, koshkinoko-hana requested changes

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/assets/home.svg
> +</svg>
нужно оставлять пустую строку
вроде как в линте это прописано

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/NewsCard/NewsCard.scss
> +    width: 450px;
вынеси в константу с названием $card-width, пригодится

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/NewsCard/NewsCard.scss
> +    border-radius: 25px;
нужно по возможности заменить пиксели на константы

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/NewsCard/NewsCard.scss
> +            font-weight: 300;
$font-weight-light

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/NewsCard/NewsCard.scss
> +        width: 346px;
может, сделать не фиксированную ширину, а гридом просто вёрстку с gap-ом?

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/common/icons/Slug.tsx
> +export const Slug: FC<Props> = ({onClick}) => {
Link

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/Pagination/Pagination.scss
> +    gap: 10px;
const

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/pageHeader/index.tsx
> +import {HeaderArrow} from '@common/icons/HeaderArrow'
линтер нужно прогнать

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/pageHeader/index.tsx
> +          const pathsTillCur = array.slice(0, array.indexOf(name) + 1).reduce((a: string, v: string) => a + '/' + path[v as PathKey], '')
вынеси в отдельную функцию, которая массив JSX элементов вернёт
к тому же у тебя пробег по массиву получается n*log(n) раз, а можно сделать всего n раз, если вместо slice заранее объявить константу, в которую ты будешь аккумулировать текущий путь

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/pageHeader/pageHeader.scss
> +@import '@common/styles/colors';
можно просто index заимпортировать

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/pageHeader/pageHeader.scss
> +            gap: 11px;
можем сделать gap: 10px? и константу

2023-05-16 13:11 UTC, koshkinoko-hana commented on src/client/components/pageHeader/pageHeader.scss
> +        max-width: 80%;
паддинги вместо процентов

2023-05-16 14:17 UTC, koshkinoko-hana submitted a review, later dismissed

2023-05-16 14:27 UTC, koshkinoko-hana approved these changes, later dismissed

2023-05-16 15:14 UTC, SntSwetlana commented on src/client/components/NewsCard/NewsCard.scss
> +        font-size: 22px;
размер шрифта цже идет в составе h5

2023-05-16 15:15 UTC, SntSwetlana commented on src/client/components/NewsCard/NewsCard.scss
> +        font-size: 18px;
размер шрифта идет в составе p

2023-05-16 15:27 UTC, SntSwetlana commented on src/client/components/NewsCard/NewsCard.scss
> +            font-size: 18px;
заменить на переменную

2023-05-17 09:57 UTC, koshkinoko-hana approved these changes

2023-05-17 10:01 UTC, merged