Footer
koshkinoko-hana/amm-fe pull request #5
Opened 2023-05-16 11:37 UTC by SntSwetlana

2023-05-16 12:02 UTC, koshkinoko-hana requested changes

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +        padding-bottom: 10px;
$grid-small

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +                margin: 0 10px;
$grid-small

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +                margin: 39px 0;
Цифра не очень, если это принципиально не ломает вёрстку, то лучше использовать $grid-small (40px)

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +                margin-left: 15px;
$grid-tiny-3x

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +                    align-self: self-start;
align-self работает с flex или grid. Оно точно здесь требуется?

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +          margin-right: 80px;
можно использовать $grid-small * 2

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +                  img:nth-child(1)
Подобные конструкции в css работают очень медленно. В местах, где это возможно, лучше обходиться классами. А это подходит разве что для случаев с массивами, когда навесить класс на отдельные элементы очень сложно

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +                            padding-left: 22px;
неприятная цифра, можно ли её заменить константой $grid-small*2 например?

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +        font-weight: $font-weight-normal;
Создай класс .p4 по аналогии с .p2 и заиспользуй миксин p4-desktop, стиль соответствует этому тексту

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/index.tsx
> +/* eslint-disable linebreak-style */
линт не срабатывает нормально?

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/index.tsx
> +  console.log('')
Нужно убрать

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/index.tsx
> +        <div className="copyright-text">© Факультет ПММ, 2022</div>
год лучше вычленять из текущей даты

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/index.tsx
> +                <Link to="/" className="p2"><Vk/></Link>
ссылка https://vk.com/amm_vsu
Твиттер не нужен, у факультета его нет)

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/client/components/footer/index.tsx
> +                    <span> +7 (473) 2-208-266 </span>
телефон правильнее сделать кликабельным, пример: 
<img width="306" alt="image" src="https://github.com/koshkinoko-hana/amm-fe/assets/25346736/5a38c1fa-f837-4959-b759-c79e1377d5f2">

2023-05-16 12:02 UTC, koshkinoko-hana commented on src/common/icons/icon.scss
> +
ненужное изменение

2023-05-16 12:02 UTC, koshkinoko-hana commented on tsconfig.paths.json
> +      "@/*": ["./*"],
ты используешь её для импорта файлов из папки src.В этом случае оно излишнее, так как у нас есть алиас "~/*", который и так ведёт к src.
Например:
`import IconBW from '@/src/assets/IconBw.svg'` -> `import IconBW from '~/assets/IconBw.svg'`
Кстати папка assets уже есть в  common, не стоит плодить папки в src проекта

2023-05-16 12:12 UTC, danil136 commented
![image](https://github.com/koshkinoko-hana/amm-fe/assets/77704781/c27492d3-ec8b-4998-975d-e479d125d22e)
![image](https://github.com/koshkinoko-hana/amm-fe/assets/77704781/d2bf56bc-7ae6-400a-8a69-3f6b20247c79)
падинги надо и для desktop и laptop

2023-05-16 12:17 UTC, SntSwetlana commented on src/client/components/footer/footer.scss
> +                margin: 39px 0;
$grid-medium имели ввиду?

2023-05-16 12:18 UTC, 0obitouchiha0 commented
как-нибудь уменьшить количество дивов и в принципе упростить верстку можно?

2023-05-16 13:39 UTC, SntSwetlana commented
да, если дизайнер делает это по сетке, когда есть повторимость. В нашем
случае сетки нет, а соблюсти все задумки надо. Считаем количество секций в
фигме и делаем выводы.

On Tue, May 16, 2023 at 3:18 PM danil136 ***@***.***> wrote:

> как-нибудь уменьшить количество дивов и в принципе упростить верстку можно?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/koshkinoko-hana/amm-fe/pull/5#issuecomment-1549554304>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYJ4FAYNDKQZHLDGCGDAIALXGNWBVANCNFSM6AAAAAAYDQNFH4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-16 15:58 UTC, koshkinoko-hana commented on src/client/components/footer/footer.scss
> +                margin: 39px 0;
Да

2023-05-16 19:32 UTC, SntSwetlana commented on src/client/components/footer/index.tsx
> +  console.log('')
ок

2023-05-16 19:34 UTC, SntSwetlana commented on src/client/components/footer/index.tsx
> +                    <span> +7 (473) 2-208-266 </span>
я же меняла и файл обновляла раз 10 с тех пор. Должно быть так: <a href="tel:+74732208266" className='link'>

2023-05-17 10:03 UTC, koshkinoko-hana approved these changes, later dismissed

2023-05-17 10:05 UTC, koshkinoko-hana approved these changes

2023-05-17 10:05 UTC, merged